In [3]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/alldata.csv")

Mounted at /content/drive

In [4]:
df

,Bug ID,Product,Component,Assignee,Status,Resolution,Summary,Changed
0,42629,Networking,Other,acme,NEW,---,recvmsg sleeping from invalid context,2020-12-11 06:07:53
1,42935,Networking,Other,acme,NEW,---,cannot create vlan,2016-02-15 20:05:20
2,55631,Tracing/Profiling,Perf tool,acme,NEW,---,perf report appears to misattribute samples,2015-12-10 16:07:35
3,56901,Tracing/Profiling,Perf tool,acme,NEW,---,perf report --sort segfaults with unknown keys,2013-07-08 19:16:53
4,58961,Tracing/Profiling,Perf tool,acme,NEW,---,perf probe -F does not list module functions,2019-11-14 05:22:14
...,...,...,...,...,...,...,...,...
9995,209375,ACPI,Power-Sleep-Wake,acpi_power-sleep-wake,RESOLVED,CODE_FIX,sleep does not work on HP EliteBook 845 G7 No...,2021-04-09 22:24:39
9996,29782,Drivers,Platform,acpi_power-thermal,RESOLVED,OBSOLETE,"toshiba_acpi, issues with high temperature (fa...",2012-08-16 11:08:13
9997,108831,ACPI,Power-Thermal,acpi_power-thermal,RESOLVED,INVALID,Not A Bug? - gpe4E register hight interrupts &...,2016-05-17 09:27:49
9998,203427,ACPI,Power-Video,acpi_power-video,RESOLVED,DUPLICATE,[REG 4.20 -> 5.0] AMD brightness minimum level...,2019-04-26 16:41:31
9999,8727,Drivers,Console/Framebuffers,adaplas,RESOLVED,CODE_FIX,"Garbled font in text console during boot, unti...",2007-07-19 16:56:32

'DOCUMENTED', 'OBSOLETE', 'UNREPRODUCIBLE', 'CODE_FIX',\n       'DUPLICATE', 'INSUFFICIENT_DATA', 'INVALID', 'WILL_NOT_FIX',\n       'PATCH_ALREADY_AVAILABLE', 'IMPLEMENTED', 'MOVED', 'WILL_FIX_LATER'

1.   List item
2.   List item

In [ ]:
#Lowest Priority list P1
keys = ['INVALID','WILL_NOT_FIX','INSUFFICIENT_DATA','OBSOLETE']
ignorableBugReports = df[df['Resolution'].isin(keys)]

ignorableBugReports.append(a,ignore_index=True)
ignorableBugReports

In [ ]:
#P2
#Lowest Priority list P1
keys = ['WILL_FIX_LATER','PATCH_ALREADY_AVAILABLE','UNREPRODUCIBLE']
P2BugReports = df[df['Resolution'].isin(keys)]

P2BugReports.append(a,ignore_index=True)
P2BugReports

In [5]:
import numpy as np
import collections
import re

In [6]:
df['Summary'] = df['Summary'].apply(lambda x: x.lower())

In [7]:
wordset = ()

for i in df['Summary']:
  wordset = np.union1d(wordset,re.sub(r"[^a-zA-Z0-9]", " ", i.lower()).split())

In [ ]:
for i in wordset:
  print(i)

In [9]:
def calculateBOW(wordset,str):
  tf_diz = dict.fromkeys(wordset,0)
  for word in str:
      tf_diz[word]=str.count(word)
  return tf_diz

In [ ]:
calculateBOW(wordset,df['Summary'][0])

In [15]:
import pickle
import sklearn
from sklearn.feature_extraction.text import CountVectorizer


CountVec = CountVectorizer(ngram_range=(1,1), stop_words='english')
Count_data = CountVec.fit_transform([i for i in df['Summary']])
 
#create dataframe
cv_dataframe=pd.DataFrame(Count_data.toarray(),columns=CountVec.get_feature_names_out())
cv_dataframe

,00,000,0000,00000,00000000,0000000000000000,0000000000000002,0000000000000008,0000000000000014,0000000000000018,...,zstd,zswap,zte,zurück,zxr,zxri,zyxel,导致window访问出现未知账号,而不是samba默认的nobody,设置为
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0